spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/tenant
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 60000 # 30 seconds
      pool-name: MasterHikariPool

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/initialscript
    validate-on-migrate: true
    out-of-order: false

  cloud:
    discovery:
      enabled: true

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8767/eureka

tenant:
  datasource:
    url-prefix: jdbc:mysql://localhost:3306/
    username: root
    password: password

jwt:
  secret: G9MzZjTz2Mm89rL1RL9Jb9vP0rf4pKukwH3XzOvQduE=

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  retry:
    instances:
      retry-api:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      legacy:
        enabled: true
      enabled: true

  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      circuit-breaker-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based

logging:
  level:
    com.zen.auth: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
  file:
    name: logs/authservice-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%X{sessionId}] %-5level %logger{36} - %msg%n"
